version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    build:
      context: .
    image: app:latest
    ports:
      - ${APP_PORT:-90}:90
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend

networks:
  backend:
